### ISSUE TITLE
Import with BioFormats failed

### ISSUE THREAD

**Issue by Theresa-S** [BIOP/ijp-imagetoatlas#111]
While the import of images via a QuPath project works, opening the same images (.czi, immunofluorescence pyramid images with 4 channels) with the BioFormats option fails
![grafik](https://user-images.githubusercontent.com/61883896/142424848-f0d6c5cc-0cb9-489f-a0d9-2c973f76e149.png)

and yields the following error messages:

Log:
![grafik](https://user-images.githubusercontent.com/61883896/142425157-bca12911-e65e-48ae-a0ea-767e75823163.png)

Console:
ZeissCZIReader initializing Z:\02_H+\99_Archive\P2A_Raw and processed data_before 2021\Histology\C3H\M8\NeuN-OSP-Ki67\P2-A-C3H-M8_NOK-0006-Scene-1.czi
Attempts to set opener settings for file format Zeiss CZI; data location = Z:\02_H+\99_Archive\P2A_Raw and processed data_before 2021\Histology\C3H\M8\NeuN-OSP-Ki67\P2-A-C3H-M8_NOK-0006-Scene-1.czi
[WARN] No name found for serie 1 ch 0 setting name to ch_0
[WARN] No name found for serie 2 ch 0 setting name to ch_0
java.lang.UnsupportedOperationException: Unhandled 16 bits RGB images
	at ch.epfl.biop.bdv.bioformats.bioformatssource.BioFormatsBdvSource.getBioformatsBdvSourceType(BioFormatsBdvSource.java:421)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsImageLoader.lambda$null$2(BioFormatsImageLoader.java:132)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsImageLoader.lambda$new$3(BioFormatsImageLoader.java:115)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.stream.IntPipeline$Head.forEach(IntPipeline.java:557)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsImageLoader.<init>(BioFormatsImageLoader.java:95)
	at ch.epfl.biop.bdv.bioformats.export.spimdata.BioFormatsConvertFilesToSpimData.getSpimDataInstance(BioFormatsConvertFilesToSpimData.java:261)
	at ch.epfl.biop.bdv.bioformats.export.spimdata.BioFormatsConvertFilesToSpimData.getSpimData(BioFormatsConvertFilesToSpimData.java:290)
	at ch.epfl.biop.bdv.bioformats.command.BasicOpenFilesWithBigdataviewerBioformatsBridgeCommand.run(BasicOpenFilesWithBigdataviewerBioformatsBridgeCommand.java:88)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.lang.UnsupportedOperationException: Unhandled 16 bits RGB images
	at ch.epfl.biop.bdv.bioformats.bioformatssource.BioFormatsBdvSource.getBioformatsBdvSourceClass(BioFormatsBdvSource.java:440)
	at ch.epfl.biop.bdv.bioformats.bioformatssource.BioFormatsBdvOpener.getConcreteSource(BioFormatsBdvOpener.java:404)
	at ch.epfl.biop.bdv.bioformats.bioformatssource.BioFormatsBdvOpener.getConcreteAndVolatileSources(BioFormatsBdvOpener.java:493)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsSetupLoader.<init>(BioFormatsSetupLoader.java:91)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsImageLoader.getSetupImgLoader(BioFormatsImageLoader.java:163)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsImageLoader.getSetupImgLoader(BioFormatsImageLoader.java:57)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.register(SourceAndConverterService.java:291)
	at sc.fiji.bdvpg.scijava.processors.SpimDataPostprocessor.lambda$process$0(SpimDataPostprocessor.java:64)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at sc.fiji.bdvpg.scijava.processors.SpimDataPostprocessor.process(SpimDataPostprocessor.java:59)
	at org.scijava.module.ModuleRunner.postProcess(ModuleRunner.java:114)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:172)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ch.epfl.biop.atlas.aligner.commands.ImportImageCommand.run(ImportImageCommand.java:56)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	... 6 more
Caused by: java.lang.NullPointerException
	at ch.epfl.biop.bdv.bioformats.bioformatssource.BioFormatsBdvOpener.getConcreteAndVolatileSources(BioFormatsBdvOpener.java:496)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsSetupLoader.<init>(BioFormatsSetupLoader.java:91)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsImageLoader.getSetupImgLoader(BioFormatsImageLoader.java:163)
	at ch.epfl.biop.bdv.bioformats.imageloader.BioFormatsImageLoader.getSetupImgLoader(BioFormatsImageLoader.java:57)
	at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.register(SourceAndConverterService.java:291)
	at sc.fiji.bdvpg.scijava.processors.SpimDataPostprocessor.lambda$process$0(SpimDataPostprocessor.java:64)
	at java.util.HashMap.forEach(HashMap.java:1289)
	at sc.fiji.bdvpg.scijava.processors.SpimDataPostprocessor.process(SpimDataPostprocessor.java:59)
	at org.scijava.module.ModuleRunner.postProcess(ModuleRunner.java:114)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:172)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more

**Comment by NicoKiaru** [comment]
Right, after you told me I realized what was wrong. The problem is that I fixed this issue but not in the old version. I will try to release the next version in the following weeks, but if you want to get the updated version before maybe we can plan a small zoom session next week.

**Comment by Theresa-S** [comment]
Ah, perfect!
No problem, currently I'm fine with the QuPath option. 

Just out of curiosity: What other functionalities does the updated version have? :-)

**Comment by NicoKiaru** [comment]
Always happy to share ;-):

- Support for other atlases (including those from brainglobe)
- An extensibility mechanism to add your own registration method (even from python)
- Many bug fixes (sagittal slices has issues currently in the QuPath export)
- A code structure finally understandable
- Much better separation between the model (where are the slices, how they are transformed, what tasks are scheduled) and the view (what you see and how you interact with the model). Currently everything is mixed. But in the new version there's the model, and there is the BigDataViewer view. But you can more easily do other views (including no view for batch processing). My goal would be to experiment and try to make a 'napari view'. Or even better: have other people wanting to make a napari view ;-).

And in the not-so-long term:
- Import/export data with Imaris with the Imaris-Bridge funcion
- Data streaming from Omero
