### ISSUE TITLE
Issue with Spline registration and Edition of last registration

### ISSUE THREAD

**Issue by danielmanriquecastano** [BIOP/ijp-imagetoatlas#140]
A few weeks ago I used ABBA without major problems. However, now that I try to continue with my activities (maybe after the last update by ImageJ), I see that the Spline registration is not working, nor am I able to manually edit the registration using Edit last registration. I would be very grateful if you could look into the core of the problem. Attached are the messages displayed in the console in both cases.

Regards,

Error for Edit Last Registration:

Field UseBinaryFormatForTransformationParameters not found in itc.transforms.elastix.ElastixAffineTransform class.
Cannot append a transformation to a source of class : TransformedSource
You can try 'mutate' or wrap as transformed Source
Cannot append a transformation to a source of class : TransformedSource
You can try 'mutate' or wrap as transformed Source
Cannot append a transformation to a source of class : TransformedSource
You can try 'mutate' or wrap as transformed Source
Cannot append a transformation to a source of class : TransformedSource
You can try 'mutate' or wrap as transformed Source

Error for Spline registration

NR Converting:ch.epfl.biop.java.utilities.roi.types.TransformixOutputRoisFile->ch.epfl.biop.java.utilities.roi.types.RealPointList
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw error
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ch.epfl.biop.registration.sourceandconverter.spline.Elastix2DSplineRegistration.register(Elastix2DSplineRegistration.java:136)
	at ch.epfl.biop.atlas.aligner.SliceSources.performRegistration(SliceSources.java:542)
	at ch.epfl.biop.atlas.aligner.SliceSources.runRegistration(SliceSources.java:566)
	at ch.epfl.biop.atlas.aligner.RegisterSliceAction.run(RegisterSliceAction.java:68)
	at ch.epfl.biop.atlas.aligner.SliceSources.lambda$enqueueRunAction$1(SliceSources.java:609)
	at java.util.concurrent.CompletableFuture.uniApply(CompletableFuture.java:602)
	at java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:577)
	at java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:443)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.lang.RuntimeException: Module threw error
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:130)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NoSuchMethodError: org.ejml.factory.LinearSolverFactory.linear(I)Lorg/ejml/factory/LinearSolver;
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.computeW(ThinPlateR2LogRSplineKernelTransform.java:361)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.<init>(ThinPlateR2LogRSplineKernelTransform.java:97)
	at jitk.spline.ThinPlateR2LogRSplineKernelTransform.<init>(ThinPlateR2LogRSplineKernelTransform.java:73)
	at net.imglib2.realtransform.ThinplateSplineTransform.init(ThinplateSplineTransform.java:74)
	at net.imglib2.realtransform.ThinplateSplineTransform.<init>(ThinplateSplineTransform.java:91)
	at ch.epfl.biop.sourceandconverter.register.Elastix2DSplineRegister.run(Elastix2DSplineRegister.java:329)
	at ch.epfl.biop.scijava.command.source.register.Elastix2DSplineRegisterCommand.run(Elastix2DSplineRegisterCommand.java:39)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
[log4j] ERROR 2022-06-15 14:23:19,689 [ForkJoinPool.commonPool-worker-10] ch.epfl.biop.atlas.aligner.MultiSlicePositioner (MultiSlicePositioner.java:139) - Multipositioner : Elastix2DSplineRegistration: java.lang.RuntimeException: Module threw error
ECM_Exp2_M02_30D_Scene1.tif_ch0 slices changed
[log4j] ERROR 2022-06-15 14:23:22,516 [ForkJoinPool.commonPool-worker-10] ch.epfl.biop.atlas.aligner.MultiSlicePositioner (MultiSlicePositioner.java:124) - Action failed:Elastix 2D Spline [M].[Ch[0]].Atlas // [M].[Ch[3]].Section)] (pending)

**Comment by NicoKiaru** [comment]
thanks for the repost. 

Same issue as https://forum.image.sc/t/issue-with-spline-registration-and-edition-of-last-registration/68366

**Comment by NicoKiaru** [comment]
FIxed - incompatibility with ejml in updates sites
