### ISSUE TITLE
Thread deadlock when loading and navigating

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-imagetoatlas#151]
Relevant thread dump:

```

2022-12-30 10:43:44
Full thread dump OpenJDK 64-Bit Server VM (25.342-b07 mixed mode):


"AWT-EventQueue-0" #26 prio=6 os_prio=0 tid=0x000001f9fa9bb800 nid=0x4f14 waiting for monitor entry [0x0000008aeadfc000]
   java.lang.Thread.State: BLOCKED (on object monitor)
        at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.register(SourceAndConverterService.java:246)
        - waiting to lock <0x00000005c0032248> (a sc.fiji.bdvpg.scijava.services.SourceAndConverterService)
        at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.show(SourceAndConverterBdvDisplayService.java:262)
        at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.show(SourceAndConverterBdvDisplayService.java:241)
        at ch.epfl.biop.atlas.aligner.gui.bdv.SliceGuiState.show(SliceGuiState.java:219)
        at ch.epfl.biop.atlas.aligner.gui.bdv.SliceGuiState.sliceDisplayChanged(SliceGuiState.java:381)
        at ch.epfl.biop.atlas.aligner.gui.bdv.SliceGuiState.isCurrent(SliceGuiState.java:284)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView$$Lambda$830/570251389.accept(Unknown Source)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView$SynchronizedSliceGuiState.runSlice(BdvMultislicePositionerView.java:2340)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView.navigatePreviousSlice(BdvMultislicePositionerView.java:1573)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView.lambda$installCommonBehaviours$9(BdvMultislicePositionerView.java:265)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView$$Lambda$584/490863405.click(Unknown Source)
        at org.scijava.ui.behaviour.MouseAndKeyHandler.handleKeyPressed(MouseAndKeyHandler.java:459)
        at org.scijava.ui.behaviour.MouseAndKeyHandler.keyPressed(MouseAndKeyHandler.java:367)
        at java.awt.AWTEventMulticaster.keyPressed(AWTEventMulticaster.java:249)
        at java.awt.Component.processKeyEvent(Component.java:6497)
        at javax.swing.JComponent.processKeyEvent(JComponent.java:2832)
        at java.awt.Component.processEvent(Component.java:6316)
        at java.awt.Container.processEvent(Container.java:2239)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.KeyboardFocusManager.redispatchEvent(KeyboardFocusManager.java:1954)
        at java.awt.DefaultKeyboardFocusManager.dispatchKeyEvent(DefaultKeyboardFocusManager.java:834)
        at java.awt.DefaultKeyboardFocusManager.preDispatchKeyEvent(DefaultKeyboardFocusManager.java:1102)
        at java.awt.DefaultKeyboardFocusManager.typeAheadAssertions(DefaultKeyboardFocusManager.java:973)
        at java.awt.DefaultKeyboardFocusManager.dispatchEvent(DefaultKeyboardFocusManager.java:799)
        at java.awt.Component.dispatchEventImpl(Component.java:4760)
        at java.awt.Container.dispatchEventImpl(Container.java:2297)
        at java.awt.Window.dispatchEventImpl(Window.java:2746)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:760)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:84)
        at java.awt.EventQueue$4.run(EventQueue.java:733)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:730)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

   Locked ownable synchronizers:
        - None

"Thread-70" #269 prio=6 os_prio=0 tid=0x000001f9ff431800 nid=0x4acc in Object.wait() [0x0000008aef94e000]
   java.lang.Thread.State: WAITING (on object monitor)
        at java.lang.Object.wait(Native Method)
        at java.lang.Object.wait(Object.java:502)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1343)
        - locked <0x0000000792d31640> (a java.awt.EventQueue$1AWTInvocationLock)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
        at org.scijava.thread.DefaultThreadService.invoke(DefaultThreadService.java:115)
        at org.scijava.event.DefaultEventBus.publishNow(DefaultEventBus.java:182)
        at org.scijava.event.DefaultEventBus.publishNow(DefaultEventBus.java:73)
        at org.scijava.event.DefaultEventService.publish(DefaultEventService.java:102)
        at org.scijava.object.ObjectService.addObject(ObjectService.java:92)
        at org.scijava.object.ObjectService.addObject(ObjectService.java:86)
        at sc.fiji.bdvpg.scijava.services.SourceAndConverterService.register(SourceAndConverterService.java:275)
        - locked <0x00000005c0032248> (a sc.fiji.bdvpg.scijava.services.SourceAndConverterService)
        at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.show(SourceAndConverterBdvDisplayService.java:262)
        at sc.fiji.bdvpg.scijava.services.SourceAndConverterBdvDisplayService.show(SourceAndConverterBdvDisplayService.java:241)
        at ch.epfl.biop.atlas.aligner.gui.bdv.SliceGuiState.show(SliceGuiState.java:219)
        at ch.epfl.biop.atlas.aligner.gui.bdv.SliceGuiState.setState(SliceGuiState.java:396)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView.lambda$loadState$50(BdvMultislicePositionerView.java:891)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView$$Lambda$814/1826924754.accept(Unknown Source)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView$SynchronizedSliceGuiState.runSlice(BdvMultislicePositionerView.java:2340)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView.loadState(BdvMultislicePositionerView.java:891)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView.lambda$null$24(BdvMultislicePositionerView.java:332)
        at ch.epfl.biop.atlas.aligner.gui.bdv.BdvMultislicePositionerView$$Lambda$706/1670850851.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:750)

   Locked ownable synchronizers:
        - None


```

**Comment by NicoKiaru** [comment]
Attempted fix by removing `show()` in `SliceGuiState#setState` method
