### ISSUE TITLE
JAXB error with Rat Atlas and abba-python

### ISSUE THREAD

**Issue by NicoKiaru** [BIOP/ijp-imagetoatlas#161]
```
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw error
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ch.epfl.biop.atlas.scijava.AtlasChooserCommand.run(AtlasChooserCommand.java:72)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Module threw error
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:130)
	... 6 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBContext
	at ch.epfl.biop.atlas.rat.waxholm.spraguedawley.v4.WaxholmSpragueDawleyRatV4Ontology.initialize(WaxholmSpragueDawleyRatV4Ontology.java:59)
	at ch.epfl.biop.atlas.rat.waxholm.spraguedawley.v4p1.WaxholmSpragueDawleyRatV4p1Atlas.initialize(WaxholmSpragueDawleyRatV4p1Atlas.java:54)
	at ch.epfl.biop.atlas.rat.waxholm.spraguedawley.v4p1.command.WaxholmSpragueDawleyRatV4p1Command.run(WaxholmSpragueDawleyRatV4p1Command.java:70)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBContext
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 12 more
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw exception
	at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
	at ch.epfl.biop.atlas.scijava.AtlasPreprocessor.getValue(AtlasPreprocessor.java:60)
	at ch.epfl.biop.atlas.scijava.AtlasPreprocessor.getValue(AtlasPreprocessor.java:40)
	at net.imagej.display.process.SingleInputPreprocessor.process(SingleInputPreprocessor.java:83)
	at org.scijava.module.ModuleRunner.preProcess(ModuleRunner.java:102)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:152)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: java.lang.RuntimeException: Module threw exception
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:127)
	... 6 more
Caused by: java.lang.NullPointerException
	at org.scijava.object.ObjectIndex.getType(ObjectIndex.java:274)
	at org.scijava.object.ObjectIndex.add(ObjectIndex.java:269)
	at org.scijava.object.ObjectIndex.add(ObjectIndex.java:191)
	at org.scijava.object.NamedObjectIndex.add(NamedObjectIndex.java:50)
	at org.scijava.object.ObjectService.addObject(ObjectService.java:91)
	at org.scijava.object.ObjectService.addObject(ObjectService.java:86)
	at ch.epfl.biop.atlas.scijava.AtlasPostProcessor.lambda$process$1(AtlasPostProcessor.java:56)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1085)
	at ch.epfl.biop.atlas.scijava.AtlasPostProcessor.process(AtlasPostProcessor.java:51)
	at org.scijava.module.ModuleRunner.postProcess(ModuleRunner.java:114)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:172)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	... 6 more
```

**Comment by NicoKiaru** [comment]
Fixed by reverting to Java 8
