### ISSUE TITLE
Fail to insatll ABBA extension

### ISSUE THREAD

**Issue by AthiemoneZero** [BIOP/ijp-imagetoatlas#166]
Hi~ grateful for your great work on ABBA, such an amazing tool to help brain section registration. it really help a lot in my lab.

I happened to meet an error when install Qupath entension by click on automated install scripts (biop-bash-scripts-main), either from full_install or install_qupath_extensions.

It looks like thison the git bash and I have no idea this would happen:

'''
--- Installing Warpy extension
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[WARNING] 4 exceptions occurred during plugin discovery.
 --- Setting global cache
Global cache set to 18338 Mb, out of 36677 Mb available (50%)
[WARN] Overriding action BDV - Set BDV window (biop)
[INFO] Overriding BIOP Run Macro...; identifier: command:ch.epfl.biop.macrorunner.B_Run_Macro; jar: file:/I:/CXC/ABBA/Fiji.app/plugins/BIOP/B_Run_Macro-1.0.0-SNAPSHOT.jar
true
--- Installing ABBA extension
defaultQuPathUserPath="I:/CXC/ABBA//QuPath_Common_Data_0.4",quPathPrefsNode="io.github.qupath/0.4",quPathExtensionURL="https://github.com/BIOP/qupath-extension-abba/releases/download/0.1.4/qupath-extension-abba-0.1.4.zip",quitAfterInstall="true"
OpenJDK 64-Bit Server VM warning: ignoring option PermSize=128m; support was removed in 8.0
OpenJDK 64-Bit Server VM warning: Using incremental CMS is deprecated and will likely be removed in a future release
[WARNING] 4 exceptions occurred during plugin discovery.
 --- Setting global cache
Global cache set to 18338 Mb, out of 36677 Mb available (50%)
[WARN] Overriding action BDV - Set BDV window (biop)
[INFO] Overriding BIOP Run Macro...; identifier: command:ch.epfl.biop.macrorunner.B_Run_Macro; jar: file:/I:/CXC/ABBA/Fiji.app/plugins/BIOP/B_Run_Macro-1.0.0-SNAPSHOT.jar
true
[ERROR] java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:476)
        at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:470)
        at sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:160)
        at sun.security.ssl.SSLTransport.decode(SSLTransport.java:110)
        at sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1418)
        at sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1324)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:439)
        at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:410)
        at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:197)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1577)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1505)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
        at java.net.URL.openStream(URL.java:1093)
        at org.apache.commons.io.FileUtils.copyURLToFile(FileUtils.java:1025)
        at org.apache.commons.io.FileUtils$copyURLToFile.call(Unknown Source)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:148)
        at InstallQuPathExtension.run(InstallQuPathExtension.groovy:118)
        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:317)
        at org.codehaus.groovy.jsr223.GroovyScriptEngineImpl.eval(GroovyScriptEngineImpl.java:155)
        at org.scijava.plugins.scripting.groovy.GroovyScriptLanguage$1.eval(GroovyScriptLanguage.java:97)
        at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
        at org.scijava.script.ScriptModule.run(ScriptModule.java:157)
        at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
        at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
        at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)

'''

Really apreciate any helpful conmment

**Comment by AthiemoneZero** [comment]
although this bug exists, I can open ABBA and do normal registration work until I use elastix. I've debug the problems of elastix (from this try: https://forum.image.sc/t/abba-experimental-a-fiji-qupath-workflow-for-mouse-brain-slice-registration-to-the-allen-brain-atlas-ccfv3/54345/28), but this annoying bug is still here. 

I find the log turns out that conda.bat is not a commond or bash file in my cmd. But when I just open cmd and type conda or conda.bat, this commond works well and I did set my sys.path to the right fold of anaconda.

Strangly, and I am still troubled here. Look forward to your help!

**Comment by NicoKiaru** [comment]
The install scripts are lagging behind... I'll try to find some time to fix them.
I think the problem comes from https://github.com/BIOP/biop-bash-scripts/issues/8

There should be a way to avoid this issue, but I do not have time to fix it before next week. Sorry

**Comment by NicoKiaru** [comment]
Well, it's been way more than a week 😓. But the issue was fixed in July last year.
