### ISSUE TITLE
ABBA not compatible with elastix 5.1.0

### ISSUE THREAD

**Issue by GuillaumeLeGoc** [BIOP/ijp-imagetoatlas#171]
Hey there,
Not sure if you prefer Image.sc forums for issues but here I am.
First, thanks for this promising pipeline !

I am using Windows 10, I installed ABBA for Fiji following the [step-by-step manual installation](https://biop.github.io/ijp-imagetoatlas/installation.html#step-by-step-manual-installation). I installed the latest Elastix (5.1.0).
I'm using a sample stack of 5 TIFF images, with 4 channels, calibrated (1 pixel = 2 microns), pyramidal (with Kheops), QuPath sees them well, knows the pixel size and the multi-resolutions.
ABBA sees the images as well, are properly calibrated, all channels look good, I can manipulate the slices, reorder, move, manually transform them (with the interactive tool). DeepSlice registration works.

Here's the problem :
When I select a slice and perform Align > ABBA - Elastix Registration (Affine), with channels 0 for atlas and slices, the task never gets done (processors remain idle), the label "R" stays yellow, on the top left it is written "[...] (pending)" and on the bottom right there's this circle saying it's doing something on slice n.
The console outputs this error : 
```
> java.lang.UnsupportedOperationException  
> 	at itc.transforms.elastix.ElastixTransform.load(ElastixTransform.java:266)  
> 	at ch.epfl.biop.sourceandconverter.register.Elastix2DAffineRegister.run(Elastix2DAffineRegister.java:160)  
> 	at ch.epfl.biop.scijava.command.source.register.Elastix2DAffineRegisterCommand.run(Elastix2DAffineRegisterCommand.java:72)  
> 	at org.scijava.command.CommandModule.run(CommandModule.java:196)  
> 	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:163)  
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)  
> 	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)  
> 	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)  
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)  
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)  
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)  
> 	at java.lang.Thread.run(Thread.java:750)  
> [ERROR] Error during registration
> 
```
It is definitely an error with Elastix but it doesn't seem to provide any detail on  the actual error. I did setup the elastix.exe and transformix.exe in BIOP > Set and Check Wrappers, and they work, given the test provided by [this groovy script](https://forum.image.sc/t/abba-experimental-a-fiji-qupath-workflow-for-mouse-brain-slice-registration-to-the-allen-brain-atlas-ccfv3/54345/28).

So... I'm at loss here, any suggestions are welcome. If I can provide any further details, let me know !
Is there a way to recover the actual elastix command generated by ABBA to try it directly from the Windows command prompt to see what Elastix says ?

Cheers !

**Comment by GuillaumeLeGoc** [comment]
Small note : [elastix 5.2.0](https://github.com/SuperElastix/elastix/releases/tag/5.2.0) does not work either.

**Comment by NicoKiaru** [comment]
Documentation needs to be updated

**Comment by NicoKiaru** [comment]
Done in documentation - to be released
