### ISSUE TITLE
Error using ABBA using Installation via Windows Installer

### ISSUE THREAD

**Issue by Sarruedi** [BIOP/ijp-imagetoatlas#191]
Hi Nico,

I'm trying to use ABBA for the first time and have tried installing ABBA and its dependencies via the brand-new Windows Installer. 
The installation itself seems to go through without an obvious error, but once I start ABBA in ImageJ, I get the following error message and I wonder whether you have any advice on how to fix these:

```
hdf5 file already downloaded - skipping
xml file already downloaded - skipping
Ontology file already downloaded - skipping
Spimdata mpicbg.spim.data.SpimData@4d4081eb is using the Bdv Playground global cache.
[WARNING] Ignoring unsupported output: ba [ch.epfl.biop.atlas.mouse.allen.ccfv3p1.command.AllenBrainAdultMouseAtlasCCF2017v3p1Command]
[WARNING] Ignoring unsupported output: atlas [ch.epfl.biop.atlas.mouse.allen.ccfv3p1.command.AllenBrainAdultMouseAtlasCCF2017v3p1Command]
[ERROR] Command errored: ABBA - Align Big Brains and Atlases (no GUI)
java.lang.ExceptionInInitializerError
	at sc.fiji.bdvpg.sourceandconverter.SourceAndConverterHelper.cloneConverter(SourceAndConverterHelper.java:219)
	at sc.fiji.bdvpg.sourceandconverter.transform.SourceAffineTransformer.apply(SourceAffineTransformer.java:101)
	at sc.fiji.bdvpg.sourceandconverter.transform.SourceAffineTransformer.get(SourceAffineTransformer.java:83)
	at ch.epfl.biop.atlas.aligner.ReslicedAtlas.computeReslicedSources(ReslicedAtlas.java:222)
	at ch.epfl.biop.atlas.aligner.ReslicedAtlas.setResolution(ReslicedAtlas.java:83)
	at ch.epfl.biop.atlas.aligner.command.ABBAStartCommand.run(ABBAStartCommand.java:57)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Couldn't find pwsh.exe or powershell.exe on path or in default system locations
	at dev.dirs.Util.windowsFallback(Util.java:284)
	at dev.dirs.Util.getWinDirs(Util.java:166)
	at dev.dirs.ProjectDirectories.fromPath(ProjectDirectories.java:255)
	at dev.dirs.ProjectDirectories.from(ProjectDirectories.java:309)
	at bdv.BigDataViewer.<clinit>(BigDataViewer.java:112)
	... 15 more
Caused by: java.io.IOException: Cannot run program "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe": CreateProcess error=225, Operation did not complete successfully because the file contains a virus or potentially unwanted software
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at dev.dirs.Util.runCommands(Util.java:197)
	at dev.dirs.Util.runWinCommands(Util.java:233)
	at dev.dirs.Util.windowsFallback(Util.java:282)
	... 19 more
Caused by: java.io.IOException: CreateProcess error=225, Operation did not complete successfully because the file contains a virus or potentially unwanted software
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:453)
	at java.lang.ProcessImpl.start(ProcessImpl.java:139)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 22 more
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Module threw error
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ch.epfl.biop.atlas.aligner.gui.bdv.ABBABdvStartCommand.run(ABBABdvStartCommand.java:48)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Module threw error
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:131)
	... 6 more
Caused by: java.lang.ExceptionInInitializerError
	at sc.fiji.bdvpg.sourceandconverter.SourceAndConverterHelper.cloneConverter(SourceAndConverterHelper.java:219)
	at sc.fiji.bdvpg.sourceandconverter.transform.SourceAffineTransformer.apply(SourceAffineTransformer.java:101)
	at sc.fiji.bdvpg.sourceandconverter.transform.SourceAffineTransformer.get(SourceAffineTransformer.java:83)
	at ch.epfl.biop.atlas.aligner.ReslicedAtlas.computeReslicedSources(ReslicedAtlas.java:222)
	at ch.epfl.biop.atlas.aligner.ReslicedAtlas.setResolution(ReslicedAtlas.java:83)
	at ch.epfl.biop.atlas.aligner.command.ABBAStartCommand.run(ABBAStartCommand.java:57)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	... 6 more
Caused by: java.lang.RuntimeException: Couldn't find pwsh.exe or powershell.exe on path or in default system locations
	at dev.dirs.Util.windowsFallback(Util.java:284)
	at dev.dirs.Util.getWinDirs(Util.java:166)
	at dev.dirs.ProjectDirectories.fromPath(ProjectDirectories.java:255)
	at dev.dirs.ProjectDirectories.from(ProjectDirectories.java:309)
	at bdv.BigDataViewer.<clinit>(BigDataViewer.java:112)
	... 15 more
Caused by: java.io.IOException: Cannot run program "C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe": CreateProcess error=225, Operation did not complete successfully because the file contains a virus or potentially unwanted software
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
	at dev.dirs.Util.runCommands(Util.java:197)
	at dev.dirs.Util.runWinCommands(Util.java:233)
	at dev.dirs.Util.windowsFallback(Util.java:282)
	... 19 more
Caused by: java.io.IOException: CreateProcess error=225, Operation did not complete successfully because the file contains a virus or potentially unwanted software
	at java.lang.ProcessImpl.create(Native Method)
	at java.lang.ProcessImpl.<init>(ProcessImpl.java:453)
	at java.lang.ProcessImpl.start(ProcessImpl.java:139)
	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
	... 22 more
```

**Comment by NicoKiaru** [comment]
Oh, whoa! Super weird...

Could it your antivirus ?

You can try to run Fiji first as a standalone application and see if it works (not all functionality will work, but at least you can test if this message disappear). The shipped executable Fiji is in:

```
C:\Users\username\AppData\Local\abba-python-0.8.0\win\Fiji.app
```

Or, I believe, in 

```
C:\ProgramData\abba-python-0.8.0\win\Fiji.app
```

if ABBA was installed for all users

**Comment by NicoKiaru** [comment]
You're running the headless version of ABBA (`ABBA - Align Big Brains and Atlases (no GUI)`): is this on purpose ? Do you get the same message if you run `ABBA - ABBA Start` ?

![image](https://github.com/BIOP/ijp-imagetoatlas/assets/20223054/866af637-0c1f-47a5-8eed-06dababeb975)

**Comment by NicoKiaru** [comment]
@tpietzsch (just to let you know, no need to do anything)

There seem to be an issue in some weird scenario (pyimagej) in a static initializer of the BigDataViewer class:

```
Caused by: java.lang.RuntimeException: Couldn't find pwsh.exe or powershell.exe on path or in default system locations
	at dev.dirs.Util.windowsFallback(Util.java:284)
	at dev.dirs.Util.getWinDirs(Util.java:166)
	at dev.dirs.ProjectDirectories.fromPath(ProjectDirectories.java:255)
	at dev.dirs.ProjectDirectories.from(ProjectDirectories.java:309)
	at bdv.BigDataViewer.<clinit>(BigDataViewer.java:112)
	... 15 more
```

**Comment by NicoKiaru** [comment]
Ah, there is the line that causes issues:

https://github.com/bigdataviewer/bigdataviewer-core/blob/c47e2370ae9b9e281444f127cb36cd9ef1497336/src/main/java/bdv/BigDataViewer.java#L112

**Comment by NicoKiaru** [comment]
Maybe it's linked to this bug:

https://github.com/dirs-dev/directories-jvm/issues/28

and they have been suffering with windows:

https://github.com/dirs-dev/directories-jvm/issues/49

@tpietzsch would it be ok if I try to file a PR that would catch the error inside a static initializer bloc, or do you think there's a better option ?

**Comment by Sarruedi** [comment]
I tried deactivating the antivirus, but so far no luck. But I agree that one issue may be related to the antivirus; also got a 225 error when trying to pip install DeepSlice on its own.

**Comment by NicoKiaru** [comment]
Ah so maybe it's more general security issue, so it's probably not worth changing anything codewise for now.

**Comment by NicoKiaru** [comment]
As part of testing, you can try to run ABBA in administrator mode (or try to pip install DeepSlice and see if it works).

**Comment by Sarruedi** [comment]
Yes, exactly the same error, probably installation issue. Unfortunately installing components individually still causes issues, but it seems to have to do with DeepSlice:

Collecting DeepSlice
  Using cached DeepSlice-1.1.6-py3-none-any.whl (24 kB)
Collecting protobuf==3.20
  Downloading protobuf-3.20.0-cp310-cp310-win_amd64.whl (903 kB)
     ---------------------------------------- 903.8/903.8 kB 5.2 MB/s eta 0:00:00
Collecting DeepSlice
  Using cached DeepSlice-1.1.5-py3-none-any.whl (35 kB)
  Using cached DeepSlice-1.1.4-py3-none-any.whl (35 kB)
  Using cached DeepSlice-1.1.3-py3-none-any.whl (35 kB)
  Using cached DeepSlice-1.1.2-py3-none-any.whl (34 kB)
  Using cached DeepSlice-1.1.1-py3-none-any.whl (34 kB)
  Using cached DeepSlice-1.1.0-py3-none-any.whl (34 kB)
  Using cached DeepSlice-1.0.11-py3-none-any.whl (33 kB)
  Using cached DeepSlice-1.0.6-py3-none-any.whl (33 kB)
  Using cached DeepSlice-1.0.5.tar.gz (31 kB)
  ERROR: Error [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software while executing command python setup.py egg_info
  Preparing metadata (setup.py) ... error
ERROR: Could not install packages due to an OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software

**Comment by NicoKiaru** [comment]
Did you use the installer ? If yes, this last error should not happen...

You can fix it by copying [this file](https://github.com/BIOP/ijl-utilities-wrappers/blob/master/src/main/resources/deepslice_cli_v1.1.5.1.py) to the indicated location (`C:\Users\username\.conda\envs\deepslice`)

**Comment by Sarruedi** [comment]
Yeah, I used the 'ABBA package' Windows installer in the end as I kept getting errors trying to install DeepSlice on its own (Tensorflow version incompatibility)
