### ISSUE TITLE
Doesnt launch on linux

### ISSUE THREAD

**Issue by PolarBean** [BIOP/ijp-imagetoatlas#71]
I am excited to try the project :)
The issue I am having is that ABBA downloads the correct atlas files it refuses to launch, it may be as I am using manjaro linux. 
here is the console log from ImageJ
Any idea what I could be doing wrong? I'm happy to reinstall on windows if you recommend that. 

-----------------------------------------------------------------------------------------
`hdf5 file already downloaded - skipping
xml file already downloaded - skipping
Ontology file already downloaded - skipping
[ERROR] Module threw exception
java.util.NoSuchElementException
	       at java.util.Scanner.throwFor(Scanner.java:862)
	   at java.util.Scanner.next(Scanner.java:1371)
	   at ch.epfl.biop.atlas.allen.AllenOntology.streamToString(AllenOntology.java:115)
	   at ch.epfl.biop.atlas.allen.AllenOntology.jsonGetRequest(AllenOntology.java:107)
	   at ch.epfl.biop.atlas.allen.AllenOntology.fetchOntologyJSON(AllenOntology.java:83)
	   at ch.epfl.biop.atlas.allen.AllenOntology.initialize(AllenOntology.java:75)
	   at ch.epfl.biop.atlas.allen.AllenAtlas.initialize(AllenAtlas.java:19)
	   at ch.epfl.biop.atlas.allen.adultmousebrain.AllenBrainAdultMouseAtlasCCF2017.run(AllenBrainAdultMouseAtlasCCF2017.java:53)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.util.concurrent.ExecutionException: java.util.NoSuchElementException
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at ch.epfl.biop.atlas.ABBACommand.run(ABBACommand.java:62)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.NoSuchElementException
	at java.util.Scanner.throwFor(Scanner.java:862)
	at java.util.Scanner.next(Scanner.java:1371)
	at ch.epfl.biop.atlas.allen.AllenOntology.streamToString(AllenOntology.java:115)
	at ch.epfl.biop.atlas.allen.AllenOntology.jsonGetRequest(AllenOntology.java:107)
	at ch.epfl.biop.atlas.allen.AllenOntology.fetchOntologyJSON(AllenOntology.java:83)
	at ch.epfl.biop.atlas.allen.AllenOntology.initialize(AllenOntology.java:75)
	at ch.epfl.biop.atlas.allen.AllenAtlas.initialize(AllenAtlas.java:19)
	at ch.epfl.biop.atlas.allen.adultmousebrain.AllenBrainAdultMouseAtlasCCF2017.run(AllenBrainAdultMouseAtlasCCF2017.java:53)`

**Comment by PolarBean** [comment]
My fault, made a mistake in my QuPath installation, and did not make the extensions subdirectory.
