### ISSUE TITLE
Registration not updating when aligning with Deepslice

### ISSUE THREAD

**Issue by enassar** [BIOP/ijp-imagetoatlas#97]
Hello,

Lately my colleagues and I haven't been able to register our data with Deepslice on ABBA. Making the results.xml file works, but after putting it in the relevant folder, when pressing ok nothing changes. The following error shows up in the log:

```
[ERROR] Module threw exception
java.lang.NullPointerException
	at ch.epfl.biop.atlas.aligner.commands.RegistrationDeepSliceCommand.adjustSlicesZPosition(RegistrationDeepSliceCommand.java:315)
	at ch.epfl.biop.atlas.aligner.commands.RegistrationDeepSliceCommand.run(RegistrationDeepSliceCommand.java:177)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

We'd love some help with this!

Best wishes,
Estelle

Full log below:
```
[WARNING] Ignoring unsupported output: ba [ch.epfl.biop.atlas.allen.adultmousebrain.AllenBrainAdultMouseAtlasCCF2017]
Creating instance
[ERROR] SourceSelectorBehaviour or EditorBehaviourInstaller cannot be retrieved. Cannot uninstall EditorBehaviour
Animator thread started
Registration plugin IdentityRegistrationCommand discovered
Registration plugin RegistrationElastixAffineCommand discovered
Registration plugin RegistrationElastixAffineRemoteCommand discovered
Registration plugin RegistrationBigWarpCommand discovered
Registration plugin RegistrationElastixSplineCommand discovered
Registration plugin RegistrationElastixSplineRemoteCommand discovered
Instance created
[WARNING] Ignoring unsupported output: mp [ch.epfl.biop.atlas.aligner.MultiSlicePositioner]
[WARNING] Ignoring unsupported output: mp [ch.epfl.biop.atlas.aligner.MultiSlicePositioner]
OMETiffReader initializing D:\Estelle\data\RNAscope\PW166\split_sections\PW166-A06_Scan1_[6054,30911]_component_data_merged_Region 1.ome.tif
Reading IFDs
Populating metadata
[WARN] Could not access omeMeta.getPlanePosition serie 0
[WARN] Could not access omeMeta.getPlanePosition serie 0
[WARN] Could not access omeMeta.getPlanePosition serie 0
[WARN] Could not access omeMeta.getPlanePosition serie 0
[WARN] Could not access omeMeta.getPlanePosition serie 0
[WARN] Could not access omeMeta.getPlanePosition serie 0
[WARN] Could not access omeMeta.getPlanePosition serie 0
ch.epfl.biop.java.utilities.roi.ConvertibleRois
Creating slice PW166-A06_Scan1_[6054,30911]_component_data_merged_Region 1.ome.tif_DAPI...
Slice PW166-A06_Scan1_[6054,30911]_component_data_merged_Region 1.ome.tif_DAPI created!
Multipositioner : Slice added
[WARNING] Ignoring unsupported output: ds [spimdata.util.Displaysettings]
Export of slice PW166-A06_Scan1_[6054,30911]_component_data_merged_Region 1.ome.tif_DAPI done (1/1)
Export as QuickNii Dataset done - Folder : D:\Estelle\test\deepslice
[ERROR] Module threw exception
java.lang.NullPointerException
	at ch.epfl.biop.atlas.aligner.commands.RegistrationDeepSliceCommand.adjustSlicesZPosition(RegistrationDeepSliceCommand.java:315)
	at ch.epfl.biop.atlas.aligner.commands.RegistrationDeepSliceCommand.run(RegistrationDeepSliceCommand.java:177)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:124)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:63)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by NicoKiaru** [comment]
Thanks for the report! I actually have a comment that says null pointer exception next this line - which means that I already had this bug once, but I was unable to fix, probably because I can't reproduce it reliably. I'll try to rewrite this part to make it more robust or at least to make it more explicit regarding the origin of the error

**Comment by enassar** [comment]
Alright, thanks Nico!
